export * from "./ClinicInfo";
export * from "./DoctorProfile";
export * from "./Home";
export * from "./Login";
export * from "./Profile";
export * from "./Appointment";
export * from "./Signup";
export * from "./AdminDashboard";
export * from "./OTP";
export * from "./DoctorCards"
